// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQ7HmB3qeHcaoLGUrx4ykvsagPd67l7c',
    appId: '1:442626263403:android:b480b82d0c700fc9ad642e',
    messagingSenderId: '442626263403',
    projectId: 'ministeriodelouvor-618d4',
    storageBucket: 'ministeriodelouvor-618d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1QDobxQLl6Jd61qAuGB49qRJNjzmq1O8',
    appId: '1:442626263403:ios:54eda01548b227a6ad642e',
    messagingSenderId: '442626263403',
    projectId: 'ministeriodelouvor-618d4',
    storageBucket: 'ministeriodelouvor-618d4.firebasestorage.app',
    iosBundleId: 'com.example.ministerioDeLouvor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1QDobxQLl6Jd61qAuGB49qRJNjzmq1O8',
    appId: '1:442626263403:ios:54eda01548b227a6ad642e',
    messagingSenderId: '442626263403',
    projectId: 'ministeriodelouvor-618d4',
    storageBucket: 'ministeriodelouvor-618d4.firebasestorage.app',
    iosBundleId: 'com.example.ministerioDeLouvor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACugDTzCyUzsYDA9O6tIG4B6mRHfN4uBI',
    appId: '1:442626263403:web:070b195a359119c6ad642e',
    messagingSenderId: '442626263403',
    projectId: 'ministeriodelouvor-618d4',
    authDomain: 'ministeriodelouvor-618d4.firebaseapp.com',
    storageBucket: 'ministeriodelouvor-618d4.firebasestorage.app',
    measurementId: 'G-L5W9SQJRZH',
  );
}
